name: Deploy to Amazon ECS CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: dev-daitssu-crawl
  ECS_SERVICE: dev-daitssu-crawler
  ECS_CLUSTER: dev-daitssu
  ECS_TASK_DEFINITION: task-definition.json # set this to the path to your Amazon ECS task definition
  #  # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: dev-daitssu-crawl
  # containerDefinitions section of your task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Add Configuration
        env:
          CRAWL_DEV_SECRET: ${{secrets.CRAWL_DEV_CONFIGURATION}}
        run: echo -e $CRAWL_DEV_SECRET > configuration.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:latest" >> $GITHUB_OUTPUT

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HH-mm-ss
          utcOffset: "+09:00"

      - name: Deploy
        id: deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-2
          application_name: daitssu-crawl
          environment_name: daitssu-crawl-develop
          version_label: earth-docker-${{steps.current-time.outputs.formattedTime}}
          deployment_package: docker-compose.yaml
          wait_for_environment_recovery: 300
